import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faSync,
  faCaretUp,
  faCaretDown,
  faExclamationCircle,
  faSearch,
  faSort,
  faSortUp,
  faSortDown,
  faChevronDown,
  faChevronUp,
  faChevronRight,
  faChevronLeft,
  faEdit,
  faPen,
  faTrash,
  faUndo,
  faTimes,
  faAsterisk,
  faUserCircle,
  faSpinner,
  faBriefcase,
  faFileInvoiceDollar,
  faCalendarCheck,
  faMoneyBillAlt,
  faRocket,
  faTachometerAlt,
  faPlay,
  faStop,
  faTimesCircle,
  faPlus,
  faHeartBroken,
  faDollarSign,
} from '@fortawesome/pro-solid-svg-icons';

import {
  faTimesCircle as farTimesCircle,
  faCompressAlt as farCompressAlt,
  faExpandAlt as farExpandAlt,
  faCalendarAlt as farCalendarAlt
} from '@fortawesome/pro-regular-svg-icons';

import {
  faGrinBeamSweat as falGrinBeamSweat,
  faTimes as falTimes,
  faChevronCircleRight as falChevronCircleRight,
  faChevronCircleLeft as falChevronCircleLeft,
  faArrowUp as falArrowUp,
  faArrowDown as falArrowDown,
  faInfoCircle as falInfoCircle,
  faExclamationCircle as falExclamationCircle,
  faExclamationTriangle as falExclamationTriangle,
  faCheckCircle as falCheckCircle,
  faChevronLeft as falChevronLeft,
  faLightbulb as falLightbulb
} from '@fortawesome/pro-light-svg-icons';

import { faGoogle } from '@fortawesome/free-brands-svg-icons';

/* Add icons to library */
library.add(
  faSync,
  faCaretDown,
  faCaretUp,
  faExclamationCircle,
  faSearch,
  faSort,
  faSortUp,
  faSortDown,
  faChevronDown,
  faChevronUp,
  faChevronRight,
  faChevronLeft,
  faEdit,
  faPen,
  faTrash,
  faUndo,
  faTimes,
  faAsterisk,
  faSpinner,
  faUserCircle,
  faBriefcase,
  faFileInvoiceDollar,
  faCalendarCheck,
  faMoneyBillAlt,
  faRocket,
  faTachometerAlt,
  faPlay,
  faStop,
  faTimesCircle,
  farTimesCircle,
  falGrinBeamSweat,
  faPlus,
  faGoogle,
  faHeartBroken,
  faDollarSign,
  falTimes,
  farCompressAlt,
  falChevronCircleRight,
  falChevronCircleLeft,
  farCalendarAlt,
  falArrowUp,
  falArrowDown,
  farExpandAlt,
  falInfoCircle,
  falExclamationCircle,
  falExclamationTriangle,
  falCheckCircle,
  falChevronLeft,
  falLightbulb
);
