import './index';

/* Export icons name */
export enum IconName {
  SYNC = 'sync',
  CARET_UP = 'caret-up',
  CARET_DOWN = 'caret-down',
  EXCLAMATION_CIRCLE = 'exclamation-circle',
  SEARCH = 'search',
  SORT = 'sort',
  SORT_UP = 'sort-up',
  SORT_DOWN = 'sort-down',
  CHEVRON_DOWN = 'chevron-down',
  CHEVRON_UP = 'chevron-up',
  CHEVRON_RIGHT = 'chevron-right',
  CHEVRON_LEFT = 'chevron-left',
  EDIT = 'edit',
  PEN = 'pen',
  TRASH = 'trash',
  UNDO = 'undo',
  CLOSE = 'times',
  CLOSE_CIRCLE = 'times-circle',
  ASTERISK = 'asterisk',
  SPINNER = 'spinner',
  USER = 'user-circle',
  BRIEFCASE = 'briefcase',
  INVOICE_DOLLAR = 'file-invoice-dollar',
  CALENDAR_CHECK = 'calendar-check',
  MONEY_BILL_ALT = 'money-bill-alt',
  ROCKET = 'rocket',
  TACHOMETER_FAST = 'tachometer-alt',
  PLAY = 'play',
  STOP = 'stop',
  GRIN_BEAM_SWEAT = 'grin-beam-sweat',
  PLUS = 'plus',
  GOOGLE = 'google',
  HEART_BROKEN = 'heart-broken',
  COMPRESS_ALT = 'compress-alt',
  EXPAND_ALT = 'expand-alt',
  CHEVRON_CIRCLE_LEFT = 'chevron-circle-left',
  CHEVRON_CIRCLE_RIGHT = 'chevron-circle-right',
  CALENDAR_ALT = 'calendar-alt',
  ARROW_UP = 'arrow-up',
  ARROW_DOWN = 'arrow-down',
  INFO_CIRCLE = 'info-circle',
  EXCLAMATION_TRIANGLE = 'exclamation-triangle',
  CHECK_CIRCLE = 'check-circle',
  DOLLAR = 'dollar-sign',
  LIGHT_BULB = 'lightbulb',
  SIGN_OUT_ALT = 'sign-out-alt',
  CHART_PIE = 'chart-pie',
  CLOCK = 'clock',
}
